'use strict';
const $=id=>document.getElementById(id), esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const phaseNames={awaiting:'待你审阅',needs_student:'需要修改',revision_ready:'已排队',queued:'已排队',working:'正在撰写',rewriting:'按意见修改中',reviewing:'独立复审中',delivery_pending:'发布产物中',failed:'处理遇到问题',submitted:'已提交学堂',approval_invalid:'需要重新确认',closed_remote:'学堂作业已关闭',submission_unknown:'提交结果待确认'};
const kinds={courseware:'课件 / 补充资料',assignment:'作业附件',notice:'公告',artifact:'产物',source:'报告源文件'};
const harness=name=>name==='claude'?'Claude':name==='codex'?'Codex':'待配置';
let overview={courses:[],tasks:[],health:{}}, files=[], listed=[], currentView='overview',currentID='',courseTab='tasks',renderID=0,previewID=0,ready=false,polling=false,uploadCourse='',fileAction=null,toastTimer;
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>{$('toast').hidden=true;},4000);}
async function api(path='',body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const multipart=body instanceof FormData,res=await fetch('/api/workspace'+path,{method:body===undefined?'GET':'POST',headers:body===undefined||multipart?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:multipart?body:JSON.stringify(body),signal:controller.signal});const raw=await res.text();let data;try{data=JSON.parse(raw);}catch{data={error:raw};}if(!res.ok)throw new Error(res.status===401?'请运行 avatarthu web，或从菜单栏重新打开工作台。':data.error||'请求未完成');return data;}catch(e){if(e.name==='AbortError'||e instanceof TypeError)throw new Error('暂时连不上本机后台。后台恢复后会自动重新连接，请保留此页面。');throw e;}finally{clearTimeout(timer);}}
const accessToken=new URLSearchParams(location.hash.slice(1)).get('token');
const href=(view,id)=>'#'+new URLSearchParams({... (accessToken?{token:accessToken}:{}),view,...(id?{id}: {})});
const fileURL=(f,inline=false)=>'/api/workspace/file?'+new URLSearchParams({course:f.course_id,path:f.path,...(inline?{inline:'1'}:{})});
const date=value=>{if(!value)return '暂无';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});};
const size=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':n<1073741824?(n/1048576).toFixed(1)+' MB':(n/1073741824).toFixed(2)+' GB';
const empty=(title,detail='')=>'<div class="empty">'+esc(title)+(detail?'<p>'+esc(detail)+'</p>':'')+'</div>';
const badge=(text,tone='')=>'<span class="badge '+tone+'">'+esc(text)+'</span>';
const needsReview=t=>['awaiting','approval_invalid'].includes(t.status);
const needsHelp=t=>['needs_student','failed','submission_unknown'].includes(t.status);
const active=t=>['working','rewriting','reviewing','queued','revision_ready','delivery_pending'].includes(t.status);
function taskRow(t){return '<a class="task-row" href="'+href('task',t.id)+'"><div class="task-text"><h3>'+esc(t.title)+'</h3><small>'+esc(t.course)+' · 第 '+esc(t.revision||1)+' 版'+(t.deadline?' · 截止 '+esc(date(t.deadline)):'')+'</small></div>'+badge(phaseNames[t.status]||t.status,needsHelp(t)?'bad':needsReview(t)?'warn':'')+'</a>';}
function courseCard(c){const tasks=overview.tasks.filter(t=>t.course_id===c.id),pending=tasks.filter(needsReview).length;return '<a class="course-card" href="'+href('course',c.id)+'"><div class="course-icon">▦</div><h3>'+esc(c.name)+'</h3><p>'+esc(c.semester)+' 学期</p><footer><span>'+c.tasks+' 份作业'+(pending?' · '+pending+' 份待审阅':'')+'</span><span>进入课程 →</span></footer></a>';}
function healthHTML(h){const learn=h.learn||{},lark=h.lark||{},daemon=h.daemon||{};const rows=[{title:'网络学堂',state:learn.state==='valid'?'登录有效':learn.state==='expired'?'需要登录':learn.state==='unavailable'?'暂时无法连接':learn.state==='stale'?'保活记录待更新':learn.state==='error'?'检查未完成':'等待检查',tone:learn.state==='valid'?'good':learn.state==='expired'?'bad':'warn',detail:learn.message||'每 10 分钟保活'},{title:'飞书',state:!lark.enabled?'未启用':lark.actions==='ready'&&lark.messages==='ready'?'已连接':'连接待检查',tone:!lark.enabled?'':lark.actions==='ready'&&lark.messages==='ready'?'good':'warn',detail:!lark.enabled?'可直接在本机审阅':'卡片回调 '+(lark.actions||'未知')+' · 消息 '+(lark.messages||'未知')},...(h.cli||[]).map(c=>({title:harness(c.tool),state:{ready:'可用',unavailable:'不可用',failed:'调用失败',running:'运行中',stale:'记录待更新',unknown:'尚未检查'}[c.state]||c.state,tone:c.state==='ready'?'good':c.state==='failed'||c.state==='unavailable'?'bad':'',detail:c.reason||(c.required?'当前使用':'未用于当前分工')}))];return '<div class="health-grid">'+rows.map(r=>'<div class="health-item"><strong>'+esc(r.title)+'</strong>'+badge(r.state,r.tone)+'<p>'+esc(r.detail)+'</p></div>').join('')+'</div><div class="meta-line"><span>主写 '+harness(h.writer)+' / 复审 '+harness(h.reviewer)+'</span><span>每 '+esc(h.poll_hours||12)+' 小时扫描</span><span>下次扫描 '+esc(date(h.next_scan))+'</span><span>最近保活 '+esc(date(learn.last_success))+'</span></div>'+(daemon.problem?'<p class="error">'+esc(daemon.problem)+'</p>':'');}
function updateHealth(h){overview.health=h;const daemon=h.daemon||{},connected=daemon.state==='running'&&!daemon.problem;$('connection').textContent=connected?'本机后台运行中':'后台状态待检查';$('connection-dot').className='dot'+(connected?' ready':'');$('footer').textContent='AvatarTHU '+(h.version||'')+' · '+(connected?'本机后台运行中':'后台状态待检查')+' · 主写 '+harness(h.writer)+' / 复审 '+harness(h.reviewer);const scan=h.scan||{},busy=['queued','running'].includes(scan.state);$('scan').disabled=busy;$('scan').textContent=scan.state==='queued'?'扫描已排队':scan.state==='running'?'正在扫描…':'立即扫描';if($('health'))$('health').innerHTML=healthHTML(h);if($('scan-result'))$('scan-result').textContent=scan.state==='error'?'最近扫描失败：'+(scan.error||'未知错误'):scan.state==='completed'?'最近手动扫描完成于 '+date(scan.completed_at):busy?'扫描在后台进行，完成后会更新课程和作业。':'';}
function renderOverview(){const tasks=overview.tasks,pending=tasks.filter(needsReview),help=tasks.filter(needsHelp),todo=[...help,...pending,...tasks.filter(active)];$('content').innerHTML='<section class="hero"><div><h2>'+(pending.length?'有 '+pending.length+' 份作业等你审阅':'课程资料，集中在这里')+'</h2><p>看课程、找文件、改报告，回到同一个工作台。</p></div><span class="hero-number">'+String(overview.courses.length).padStart(2,'0')+'</span></section><div class="metrics">'+[[overview.courses.length,'门课程'],[pending.length,'份待审阅'],[tasks.filter(active).length,'份处理中'],[help.length,'份需处理']].map(([n,label])=>'<div class="metric"><strong>'+n+'</strong><span>'+label+'</span></div>').join('')+'</div><div class="section-heading"><h2>现在需要关注</h2><a href="'+href('artifacts')+'">浏览产物 →</a></div><div class="task-list">'+(todo.length?todo.map(taskRow).join(''):empty('暂时没有待办','课程扫描后，新作业会出现在这里。'))+'</div><div class="section-heading"><h2>我的课程</h2><a href="'+href('courses')+'">全部课程 →</a></div><div class="grid">'+overview.courses.slice(0,6).map(courseCard).join('')+'</div><div class="section-heading"><h2>连接与运行状态</h2><a href="'+href('settings')+'">管理设置 →</a></div><section class="panel" id="health"></section>';}
function filterBar(includeKind=true){return '<div class="filters"><input id="file-search" type="search" placeholder="搜索文件名或路径" aria-label="搜索文件名或路径">'+(currentView==='course'?'':'<select id="course-filter" aria-label="筛选课程"><option value="">所有课程</option>'+overview.courses.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('')+'</select>')+(includeKind?'<select id="kind-filter" aria-label="筛选类型"><option value="">全部类型</option>'+Object.entries(kinds).map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('')+'</select>':'')+'</div><div id="file-results"></div>';}
function fileRows(rows){if(!rows.length)return empty('没有匹配的文件','更换筛选条件，或扫描课程获取最新资料。');return '<div class="file-list">'+rows.map(f=>{const i=listed.push(f)-1,ext=f.name.includes('.')?f.name.split('.').pop().slice(0,5).toUpperCase():'FILE';return '<div class="file-row" data-editable="'+!!f.editable+'"><span class="file-icon">'+esc(ext)+'</span><div><button class="file-name" data-preview="'+i+'">'+esc(f.title||f.name)+'</button><span class="file-path">'+esc((f.course?f.course+' / ':'')+f.path)+'</span></div><span class="file-size">'+size(f.size)+'</span><span class="file-date">'+esc(date(f.modified_at))+'</span><div class="actions"><button data-preview="'+i+'">预览</button><a class="button" href="'+esc(fileURL(f))+'" download>下载</a>'+(f.editable?'<button data-rename="'+i+'">改名</button><button data-remove="'+i+'">移除</button>':'')+'</div></div>';}).join('')+'</div>';}
function renderFiles(){const q=($('file-search')?.value||'').toLocaleLowerCase(),course=$('course-filter')?.value||'',kind=$('kind-filter')?.value||'';let rows=files.filter(f=>(!q||(f.name+' '+(f.title||'')+' '+f.path+' '+f.course).toLocaleLowerCase().includes(q))&&(!course||f.course_id===course)&&(!kind||f.kind===kind));if(currentView==='artifacts')rows=rows.filter(f=>f.kind==='artifact'||f.kind==='source');if(currentView==='course'&&courseTab!=='all'){const allowed={materials:['courseware','assignment'],notices:['notice'],outputs:['artifact','source']}[courseTab];if(allowed)rows=rows.filter(f=>allowed.includes(f.kind));}listed=[];$('file-results').innerHTML='<div class="file-count">'+rows.length+' 个文件 · '+size(rows.reduce((n,f)=>n+f.size,0))+'</div>'+fileRows(rows);}
function renderCourse(c){$('content').innerHTML='<div class="actions"><span class="badge">'+esc(c.semester)+' 学期</span><button data-upload="'+c.id+'">＋ 上传补充资料</button></div><div class="tabs" role="tablist" aria-label="课程内容">'+[['tasks','作业'],['materials','课件与附件'],['notices','公告'],['outputs','产物']].map(([id,title])=>'<button role="tab" aria-selected="'+(courseTab===id)+'" class="'+(courseTab===id?'active':'')+'" data-tab="'+id+'">'+title+'</button>').join('')+'</div>'+(courseTab==='tasks'?'<div class="task-list">'+(overview.tasks.filter(t=>t.course_id===c.id).map(taskRow).join('')||empty('这门课还没有作业','课件和公告可以在上方切换查看。'))+'</div>':filterBar(false));if(courseTab!=='tasks')renderFiles();}
function textFrom(value){return typeof value==='string'?value:JSON.stringify(value,null,2);}
function reviewHTML(r){const comments=(r.comments||[]).map(c=>typeof c==='string'?esc(c):[c.severity,c.location||c.file,c.issue||c.comment||c.description,c.suggestion||c.requested_change].filter(Boolean).map(esc).join(' · ')||esc(textFrom(c)));return '<details class="review"><summary>'+badge(r.approved?'通过':'要求修改',r.approved?'good':'bad')+'<strong>第 '+esc(r.revision||'?')+' 版 · 第 '+esc(r.round||1)+' 轮</strong><small>'+harness(r.reviewer)+' · '+esc(date(r.reviewed_at))+'</small></summary><div class="review-body"><p>'+esc(r.summary||'无摘要')+'</p>'+(comments.length?'<ol>'+comments.map(c=>'<li>'+c+'</li>').join('')+'</ol>':'')+['checks','limitations'].map(key=>(r[key]||[]).length?'<small>'+(key==='checks'?'检查内容':'复审说明')+'</small><ul>'+r[key].map(v=>'<li>'+esc(textFrom(v))+'</li>').join('')+'</ul>':'').join('')+'</div></details>';}
function safeLink(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?esc(u.href):'';}catch{return '';}}
function renderTask(t){listed=[];const doc=safeLink(t.document_url),current=(t.revisions||[]).find(r=>r.revision===t.revision),history=(t.revisions||[]).filter(r=>r.revision!==t.revision);$('content').innerHTML='<div class="actions">'+badge(phaseNames[t.status]||t.status,needsHelp(t)?'bad':needsReview(t)?'warn':'')+'<a class="button primary" href="/editor#task='+encodeURIComponent(t.id)+'">编辑与审阅报告</a>'+(doc?'<a class="button" href="'+doc+'" target="_blank" rel="noopener noreferrer">飞书审阅文档 ↗</a>':'')+'<a class="button" href="'+href('course',t.course_id)+'">返回课程</a></div>'+(t.error?'<p class="error">'+esc(t.error)+'</p>':'')+'<div class="two-column"><section class="panel"><h2>作业要求</h2><p class="muted">'+esc(t.course)+(t.deadline?' · 截止 '+esc(date(t.deadline)):'')+'</p><div class="description">'+esc(t.description||'暂未同步作业描述，请查看课程中的作业附件。')+'</div>'+((t.attachments||[]).length?'<div class="section-heading"><h3>题目附件</h3></div>'+fileRows(t.attachments):'')+'</section><section class="panel"><h2>当前交付 · 第 '+esc(t.revision||1)+' 版</h2><p class="muted">进入编辑页可改正文、多段提意见，再提交定稿同步相关产物。</p><p class="muted">提交到网络学堂仍通过当前版本的飞书作业卡片确认。</p><a class="text-link" href="/api/task/'+encodeURIComponent(t.id)+'/report.html" target="_blank" rel="noopener">打开 HTML 报告预览 ↗</a><div class="meta-line"><span>最近更新 '+esc(date(t.updated_at))+'</span></div></section></div><div class="section-heading"><h2>当前产物</h2><span class="muted">第 '+esc(t.revision||1)+' 版</span></div>'+(current?fileRows(current.files):empty('这一版还没有完成的产物'))+(history.length?'<div class="section-heading"><h2>历史产物</h2></div>'+history.map(r=>'<details class="review"><summary>第 '+r.revision+' 版 · '+r.files.length+' 个文件</summary>'+fileRows(r.files)+'</details>').join(''):'')+'<div class="section-heading"><h2>独立复审记录</h2><span class="muted">'+(t.reviews||[]).length+' 次</span></div>'+((t.reviews||[]).slice().reverse().map(reviewHTML).join('')||empty('尚无复审记录'));}
function renderSettings(h){$('content').innerHTML='<div class="settings"><form id="settings-form" class="panel"><h2>作业处理方式</h2><div class="form-row">'+[['writer','主写'],['reviewer','复审']].map(([key,label])=>'<label>'+label+'<select name="'+key+'">'+['claude','codex'].map(c=>'<option value="'+c+'" '+(h[key]===c?'selected':'')+'>'+harness(c)+'</option>').join('')+'</select></label>').join('')+'</div><p class="hint">两者分别选择，可以相同。使用各自 CLI 的默认模型配置，每一阶段独立启动新会话。</p><label>课程扫描间隔（小时）<input name="poll_hours" type="number" min="0.016667" max="8760" step="any" value="'+esc(h.poll_hours||12)+'" required></label><p class="hint">默认每 12 小时扫描课程，网络学堂每 10 分钟保活。更改应用于后续任务，已开始的任务沿用启动时的分工。</p><button class="primary" type="submit">保存设置</button><span id="settings-result" class="muted" role="status"></span></form></div><div class="section-heading"><h2>运行状态</h2></div><section class="panel" id="health"></section><p class="muted" id="scan-result"></p>';}
async function renderRoute(){if(!ready)return;const id=++renderID,params=new URLSearchParams(location.hash.slice(1));currentView=params.get('view')||'overview';currentID=params.get('id')||'';const titles={overview:'总览',courses:'我的课程',course:'课程',files:'全部文件',artifacts:'交付产物',task:'作业',settings:'设置与状态'};if(!titles[currentView])currentView='overview';const section=currentView==='course'?'courses':currentView==='task'?'artifacts':currentView;document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===section));$('title').textContent=titles[currentView];$('eyebrow').textContent='AVATARTHU / '+section.toUpperCase();error('');try{if(currentView==='overview')renderOverview();else if(currentView==='courses'){$('content').innerHTML='<div class="filters"><input type="search" id="course-search" placeholder="搜索课程" aria-label="搜索课程"><select id="semester-filter" aria-label="筛选学期"><option value="">全部学期</option>'+[...new Set(overview.courses.map(c=>c.semester))].map(s=>'<option>'+esc(s)+'</option>').join('')+'</select></div><div class="grid" id="course-results"></div>';renderCourseResults();}else if(currentView==='settings')renderSettings(overview.health);else if(currentView==='task'){$('content').innerHTML=empty('正在载入作业…');const t=await api('/task/'+encodeURIComponent(currentID));if(id!==renderID)return;$('title').textContent=t.title;renderTask(t);}else{const c=overview.courses.find(c=>c.id===currentID);if(currentView==='course'&&!c)throw new Error('找不到这门课程，请返回课程列表。');$('content').innerHTML=empty('正在载入文件…');const loaded=await api('/files'+(c?'?course='+encodeURIComponent(c.id):''));if(id!==renderID)return;files=loaded;if(c){$('title').textContent=c.name;renderCourse(c);}else{$('content').innerHTML=(currentView==='artifacts'?'<p class="muted">当前与历史版本的文件均保留。查看对应作业，可以读复审意见、编辑报告。</p><div class="task-list">'+overview.tasks.filter(t=>t.artifact_count).map(taskRow).join('')+'</div><div class="section-heading"><h2>产物与源文件</h2></div>':'')+filterBar(currentView!=='artifacts');renderFiles();}}updateHealth(overview.health);}catch(e){if(id===renderID){error(e.message);$('content').innerHTML=empty('暂时无法载入','可以点击刷新重试。');}}}
function renderCourseResults(){const q=($('course-search')?.value||'').toLocaleLowerCase(),semester=$('semester-filter')?.value||'';const rows=overview.courses.filter(c=>(!q||c.name.toLocaleLowerCase().includes(q))&&(!semester||c.semester===semester));$('course-results').innerHTML=rows.map(courseCard).join('')||empty('没有匹配的课程','可以先扫描网络学堂，或更换搜索条件。');}
async function refresh(){const data=await api();overview=data;ready=true;await renderRoute();}
async function previewFile(f){const id=++previewID;await closePDF();$('preview-title').textContent=f.title||f.name;$('preview-meta').textContent=(f.course?f.course+' · ':'')+size(f.size);$('preview-download').href=fileURL(f);$('preview-body').textContent='正在载入…';if(!$('preview').open)$('preview').showModal();try{const data=await api('/preview?'+new URLSearchParams({course:f.course_id,path:f.path}));if(id!==previewID||!$('preview').open)return;const body=$('preview-body');body.replaceChildren();if(data.kind==='pdf'){await previewPDF(f,id);return;}else if(data.kind==='html'){const frame=document.createElement('iframe');frame.title=f.name;if(data.kind==='html')frame.setAttribute('sandbox','');frame.referrerPolicy='no-referrer';frame.src=fileURL(f,true);body.append(frame);}else if(data.kind==='image'){const img=document.createElement('img');img.alt=f.name;img.src=fileURL(f,true);body.append(img);}else if(data.kind==='text'){const pre=document.createElement('pre');pre.textContent=data.text;body.append(pre);}else if(data.kind==='zip'){body.innerHTML=data.entries.map(e=>'<div class="zip-entry"><span>'+esc(e.name)+'</span><small>'+size(e.size)+'</small></div>').join('')+(data.truncated?'<p class="muted">仅显示前 500 项，下载后查看完整内容。</p>':'');}else body.innerHTML=empty('此格式适合下载后查看','文件仍保存在课程目录中。');}catch(e){if(id===previewID)$('preview-body').textContent=e.message;}}
function editFile(f,action){fileAction={file:f,action};$('file-dialog-title').textContent=action==='rename'?'重命名补充资料':'移除补充资料';$('file-dialog-description').textContent=action==='rename'?f.name:'将「'+f.name+'」移到本机回收目录，后续作业不再引用它。';$('rename-label').hidden=action!=='rename';$('rename-input').required=action==='rename';$('rename-input').value=f.name;$('file-confirm').textContent=action==='rename'?'保存文件名':'移到回收目录';$('file-error').hidden=true;$('file-dialog').showModal();}
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;const d=el.dataset;if(d.close){$(d.close).close();return;}if(d.preview!==undefined){previewFile(listed[Number(d.preview)]);return;}if(d.rename!==undefined||d.remove!==undefined){editFile(listed[Number(d.rename??d.remove)],d.rename!==undefined?'rename':'remove');return;}if(d.upload){uploadCourse=d.upload;$('upload-input').click();return;}if(d.tab){courseTab=d.tab;const c=overview.courses.find(c=>c.id===currentID);renderCourse(c);}});
document.addEventListener('input',e=>{if(['file-search','course-filter','kind-filter'].includes(e.target.id))renderFiles();if(['course-search','semester-filter'].includes(e.target.id))renderCourseResults();});
document.addEventListener('submit',async e=>{if(e.target.id!=='settings-form')return;e.preventDefault();const form=e.target,button=form.querySelector('button[type=submit]');button.disabled=true;try{const data=new FormData(form),h=await api('/settings',{writer:data.get('writer'),reviewer:data.get('reviewer'),poll_hours:Number(data.get('poll_hours'))});updateHealth(h);$('settings-result').textContent='  已保存';toast('设置已保存');}catch(err){error(err.message);}finally{button.disabled=false;}});
$('file-form').addEventListener('submit',async e=>{e.preventDefault();if(!fileAction)return;const {file,action}=fileAction;$('file-confirm').disabled=true;try{const result=await api('/file-action',{course:file.course_id,path:file.path,action,name:$('rename-input').value});$('file-dialog').close();toast(result.message);await renderRoute();}catch(err){$('file-error').textContent=err.message;$('file-error').hidden=false;}finally{$('file-confirm').disabled=false;}});
$('upload-input').addEventListener('change',async e=>{const chosen=[...e.target.files];e.target.value='';if(!chosen.length)return;let count=0;try{for(const f of chosen){if(f.size>63*1024*1024)throw new Error(f.name+' 超过 63 MB，请通过本机课程目录添加。');const data=new FormData();data.append('file',f);toast('正在上传 '+f.name);await api('/upload?course='+encodeURIComponent(uploadCourse),data);count++;}toast('已加入 '+count+' 份补充资料');await renderRoute();}catch(err){error((count?'已加入 '+count+' 份资料；':'')+err.message);await renderRoute();error(err.message);}});
$('refresh').addEventListener('click',async()=>{$('refresh').disabled=true;try{await refresh();toast('已更新');}catch(e){error(e.message);}finally{$('refresh').disabled=false;}});
$('scan').addEventListener('click',async()=>{$('scan').disabled=true;try{const scan=await api('/scan',{});updateHealth({...overview.health,scan});toast('扫描已加入后台队列');}catch(e){error(e.message);$('scan').disabled=false;}});
window.addEventListener('hashchange',()=>{courseTab='tasks';renderRoute();});
async function start(){const params=new URLSearchParams(location.hash.slice(1));if(params.get('task')&&!params.get('view')){location.replace('/editor'+location.hash);return;}try{const token=params.get('token');if(token){const response=await fetch('/session',{method:'POST',headers:{'X-Editor-Token':token}});if(!response.ok)throw new Error('入口凭证无效，请运行 avatarthu web 重新打开。');document.querySelectorAll('a[href^="#view="]').forEach(a=>{const p=new URLSearchParams(a.hash.slice(1));p.set('token',token);a.hash=p.toString();});}await refresh();}catch(e){error(e.message);$('content').innerHTML=empty('等待连接本机后台','运行 avatarthu service start 后，此页会自动重连。');}setInterval(async()=>{if(polling||document.hidden)return;polling=true;try{if(!ready){await refresh();return;}const before=overview.health.scan||{},fresh=await api(),changed=JSON.stringify(fresh.tasks)!==JSON.stringify(overview.tasks)||JSON.stringify(fresh.courses)!==JSON.stringify(overview.courses),h=fresh.health;overview=fresh;updateHealth(h);if(changed&&['overview','course','courses','task','artifacts'].includes(currentView))await renderRoute();if(before.state!==h.scan?.state&&['completed','error'].includes(h.scan?.state)){if(h.scan.state==='completed')await refresh();else error('课程扫描未完成：'+(h.scan.error||'请查看运行状态'));}if($('error').textContent.startsWith('暂时连不上'))error('');}catch(e){$('connection').textContent='连接中断，正在重试';$('connection-dot').className='dot';error(e.message);}finally{polling=false;}},10000);}
start();

let pdfSession=null;
async function closePDF(){const old=pdfSession;pdfSession=null;if(old){old.render?.cancel();try{await old.loading.destroy();}catch{}}}
$('preview').addEventListener('close',()=>{previewID++;closePDF();});
async function previewPDF(file,id){
 const body=$('preview-body');body.innerHTML='<div class="pdf-controls"><button id="pdf-prev" disabled>上一页</button><label><input id="pdf-page" type="number" min="1" value="1" aria-label="PDF 页码" disabled> / <span id="pdf-count">…</span></label><button id="pdf-next" disabled>下一页</button><select id="pdf-zoom" aria-label="PDF 缩放" disabled><option value="fit">适合宽度</option><option value="1">100%</option><option value="1.5">150%</option><option value="2">200%</option></select></div><div id="pdf-status" role="status">正在打开 PDF…</div><div class="pdf-page-wrap"><canvas id="pdf-canvas" role="img" aria-label="PDF 页面"></canvas></div>';
 const lib=await import('/pdfjs/pdf.min.mjs');if(id!==previewID)return;lib.GlobalWorkerOptions.workerSrc='/pdfjs/pdf.worker.min.mjs';
 const loading=lib.getDocument({url:fileURL(file,true),cMapUrl:'/pdfjs/cmaps/',cMapPacked:true,standardFontDataUrl:'/pdfjs/standard_fonts/',wasmUrl:'/pdfjs/wasm/',isEvalSupported:false,disableAutoFetch:true,disableStream:true});
 const session={loading,document:null,page:1,render:null};pdfSession=session;
 try{session.document=await loading.promise;if(id!==previewID)return;$('pdf-count').textContent=session.document.numPages;$('pdf-page').max=session.document.numPages;
  const draw=async pageNumber=>{
   if(id!==previewID||pdfSession!==session)return;session.page=Math.max(1,Math.min(session.document.numPages,pageNumber));
   for(const key of ['pdf-prev','pdf-next','pdf-page','pdf-zoom'])$(key).disabled=true;
   $('pdf-status').textContent='正在显示第 '+session.page+' 页…';
   try{const page=await session.document.getPage(session.page);if(id!==previewID)return;const base=page.getViewport({scale:1}),zoom=$('pdf-zoom').value,scale=zoom==='fit'?Math.max(0.2,($('preview-body').clientWidth-32)/base.width):Number(zoom),viewport=page.getViewport({scale}),canvas=$('pdf-canvas'),ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.floor(viewport.width*ratio);canvas.height=Math.floor(viewport.height*ratio);canvas.style.width=Math.floor(viewport.width)+'px';canvas.style.height=Math.floor(viewport.height)+'px';canvas.setAttribute('aria-label','PDF 第 '+session.page+' 页，共 '+session.document.numPages+' 页');session.render=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:ratio===1?null:[ratio,0,0,ratio,0,0]});await session.render.promise;if(id!==previewID)return;$('pdf-page').value=session.page;$('pdf-status').textContent='';page.cleanup();
   }catch(e){if(id===previewID&&e.name!=='RenderingCancelledException')$('pdf-status').textContent='此页未能显示：'+e.message;}
   finally{if(id===previewID){$('pdf-prev').disabled=session.page<=1;$('pdf-next').disabled=session.page>=session.document.numPages;$('pdf-page').disabled=false;$('pdf-zoom').disabled=false;}}
  };
  $('pdf-prev').onclick=()=>draw(session.page-1);$('pdf-next').onclick=()=>draw(session.page+1);$('pdf-page').onchange=()=>draw(Number($('pdf-page').value)||1);$('pdf-zoom').onchange=()=>draw(session.page);await draw(1);
 }catch(e){if(id===previewID){$('pdf-status').textContent='PDF 未能打开：'+e.message+'。可以下载后查看。';await closePDF();}}
}
